import 'hybrid_logical_clock.dart';
import 'replica_id.dart';

/// Exception thrown when an observed remote [HybridLogicalClock] timestamp exceeds
/// the maximum allowed future drift threshold beyond local physical time.
class HlcFutureDriftException implements Exception {
  final int remotePhysicalTime;
  final int localPhysicalTime;
  final Duration maxFutureDrift;
  final String remoteNodeId;

  const HlcFutureDriftException({
    required this.remotePhysicalTime,
    required this.localPhysicalTime,
    required this.maxFutureDrift,
    required this.remoteNodeId,
  });

  @override
  String toString() =>
      'HlcFutureDriftException: remote physical time $remotePhysicalTime exceeds '
      'local physical time $localPhysicalTime by more than allowed drift '
      '${maxFutureDrift.inMilliseconds}ms (remote nodeId: "$remoteNodeId").';
}

/// Authoritative stateful Hybrid Logical Clock source for an active runtime writer.
/// Guarantees monotonic timestamp progression for a given [ReplicaId]:
/// every produced timestamp is strictly after all preceding timestamps generated by this clock,
/// even when physical time is unchanged or moves backward.
class StatefulHlcClock {
  /// Conservative default maximum drift allowed when observing remote timestamps (1 minute).
  static const Duration defaultMaxFutureDrift = Duration(minutes: 1);

  final ReplicaId replicaId;
  final int Function() _timeProvider;
  final Duration maxFutureDrift;
  HybridLogicalClock _latest;

  StatefulHlcClock({
    required this.replicaId,
    int Function()? timeProvider,
    HybridLogicalClock? initialClock,
    this.maxFutureDrift = defaultMaxFutureDrift,
  })  : _timeProvider =
            timeProvider ?? (() => DateTime.now().toUtc().millisecondsSinceEpoch),
        _latest = initialClock ??
            HybridLogicalClock(
              physicalTime: 0,
              logicalCounter: 0,
              nodeId: replicaId.value,
            );

  /// The most recent timestamp generated or observed by this writer.
  HybridLogicalClock get latest => _latest;

  /// Monotonically generates the next [HybridLogicalClock] timestamp for a new logical write.
  /// Guarantees `next.isAfter(previous)` under all clock conditions.
  HybridLogicalClock nextTimestamp({int offsetMs = 0}) {
    _latest = _latest.tick(
      offsetMs: offsetMs,
      timeProvider: _timeProvider,
    );
    if (_latest.nodeId != replicaId.value) {
      _latest = HybridLogicalClock(
        physicalTime: _latest.physicalTime,
        logicalCounter: _latest.logicalCounter,
        nodeId: replicaId.value,
      );
    }
    return _latest;
  }

  /// Observes a remote timestamp from another node and reconciles local clock causality.
  ///
  /// Throws [HlcFutureDriftException] if [remote.physicalTime] strictly exceeds
  /// `localPhysicalTime + maxFutureDrift`.
  /// Timestamps at exactly the drift bound (`remote.physicalTime == localPhysicalTime + maxFutureDrift`)
  /// are accepted within tolerance.
  ///
  /// A rejected remote observation does NOT mutate [_latest].
  void observeRemote(HybridLogicalClock remote, {int offsetMs = 0}) {
    final localPhysicalTime = _timeProvider() + offsetMs;
    final maxAllowedPhysicalTime =
        localPhysicalTime + maxFutureDrift.inMilliseconds;
    if (remote.physicalTime > maxAllowedPhysicalTime) {
      throw HlcFutureDriftException(
        remotePhysicalTime: remote.physicalTime,
        localPhysicalTime: localPhysicalTime,
        maxFutureDrift: maxFutureDrift,
        remoteNodeId: remote.nodeId,
      );
    }

    _latest = _latest.merge(
      remote,
      offsetMs: offsetMs,
      timeProvider: _timeProvider,
    );
    if (_latest.nodeId != replicaId.value) {
      _latest = HybridLogicalClock(
        physicalTime: _latest.physicalTime,
        logicalCounter: _latest.logicalCounter,
        nodeId: replicaId.value,
      );
    }
  }
}
