import 'hybrid_logical_clock.dart';
import 'replica_id.dart';

/// Authoritative stateful Hybrid Logical Clock source for an active runtime writer.
/// Guarantees monotonic timestamp progression for a given [ReplicaId]:
/// every produced timestamp is strictly after all preceding timestamps generated by this clock,
/// even when physical time is unchanged or moves backward.
class StatefulHlcClock {
  final ReplicaId replicaId;
  final int Function() _timeProvider;
  HybridLogicalClock _latest;

  StatefulHlcClock({
    required this.replicaId,
    int Function()? timeProvider,
    HybridLogicalClock? initialClock,
  })  : _timeProvider =
            timeProvider ?? (() => DateTime.now().toUtc().millisecondsSinceEpoch),
        _latest = initialClock ??
            HybridLogicalClock(
              physicalTime: 0,
              logicalCounter: 0,
              nodeId: replicaId.value,
            );

  /// The most recent timestamp generated or observed by this writer.
  HybridLogicalClock get latest => _latest;

  /// Monotonically generates the next [HybridLogicalClock] timestamp for a new logical write.
  /// Guarantees `next.isAfter(previous)` under all clock conditions.
  HybridLogicalClock nextTimestamp({int offsetMs = 0}) {
    _latest = _latest.tick(
      offsetMs: offsetMs,
      timeProvider: _timeProvider,
    );
    if (_latest.nodeId != replicaId.value) {
      _latest = HybridLogicalClock(
        physicalTime: _latest.physicalTime,
        logicalCounter: _latest.logicalCounter,
        nodeId: replicaId.value,
      );
    }
    return _latest;
  }

  /// Observes a remote timestamp from another node and reconciles local clock causality.
  void observeRemote(HybridLogicalClock remote, {int offsetMs = 0}) {
    _latest = _latest.merge(
      remote,
      offsetMs: offsetMs,
      timeProvider: _timeProvider,
    );
    if (_latest.nodeId != replicaId.value) {
      _latest = HybridLogicalClock(
        physicalTime: _latest.physicalTime,
        logicalCounter: _latest.logicalCounter,
        nodeId: replicaId.value,
      );
    }
  }
}
